# Generated by Django 4.1.7 on 2023-03-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasehistory',
            name='currency',
            field=models.CharField(choices=[('SA$', 'SA$'), ('SC', 'SC')], default='SC', max_length=9),
        ),
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('SA$', 'SA$'), ('SC', 'SC')], default='SC', max_length=9),
        ),
    ]
