# Generated by Django 4.1.7 on 2023-03-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='response',
            field=models.JSONField(blank=True, default={}),
        ),
        migrations.AlterField(
            model_name='command',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
