# Generated by Django 4.1.7 on 2023-03-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_command_response_alter_command_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
