# Generated by Django 4.1.7 on 2023-03-10 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.account.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('avatar', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=64, null=True)),
                ('money', models.IntegerField(default=0)),
                ('last_login', models.DateTimeField(null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('verification_code', models.IntegerField(default=0)),
            ],
            managers=[
                ('objects', src.account.managers.DiscordUserOAuth2Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=256)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
